[project]
name = "mcp-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "anthropic>=0.75.0",
    "arxiv>=2.4.0",
    "mcp>=1.25.0",
    "nest-asyncio>=1.6.0",
    "python-dotenv>=1.2.1",
]
